SELECT F.ITEM_ID, F.ITEM_NAME, F.RARITY
FROM ITEM_INFO F
JOIN ITEM_TREE T ON F.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ITEM_ID IN (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
)
ORDER BY F.ITEM_ID DESC;
